export const gameDOM = {
    common: {
        appContainer: "#app-root > .-container",
        container: ".-container",
        backgroundDiv: "div[class*=\"-backgroundImageContain\"]",
        background: "[class*=\"backgroundImageContain\"]",
        icon: "[class*=\"-backgroundImage\"]",
        hotkey: ".-commonBlockForHotKey",
        hotkeyFragment: "[class*=\"-commonBlockForHotKey\"]",
        flexDiv: "div[class*=\"-displayFlex\"]",
        boldSpan: "span.-bold",
    },
    account: {
        privateHeaderFields: ".UserInfoContainerStyle-userNameRank, .UserInfoContainerStyle-progressValue",
        clientParameter: ".ClientInfoComponentStyle-parameterText",
        currencyIcon: ".HeaderCommonStyle-icons",
        currencyValues: ".UserScoreComponentStyle-coinBlock span, .HeaderCommonStyle-icons span",
    },
    screens: {
        loadingBackground: ".ApplicationLoaderComponentStyle-container.-background",
        battleCanvas: ".BattleComponentStyle-canvasContainer",
        garage: ".GarageCommonStyle-positionContent, .GarageItemComponent-container, .ContainerInfoComponentStyle-lootBoxContainer, .GarageMainScreenStyle-blockParameters, .SkinsAndAlterationsStyle-SkinsVerticalComponent",
        lootBox: ".ContainerInfoComponentStyle-lootBoxContainer",
        shop: ".NewShopCommonComponentStyle-commonContainer",
        invitations: ".InvitationWindowsComponentStyle-centerBlock",
        progress: ".UserProgressComponentStyle-progressContainer",
    },
    dialogs: {
        container: ".DialogContainerComponentStyle-container",
        confirmation: ".DialogContainerComponentStyle-enterButton.DialogContainerComponentStyle-getRubyButton",
        contents: ".DialogContainerComponentStyle-container div",
        cancelKey: ".DialogContainerComponentStyle-keyButton",
        rubyImage: "img[src*=\"rubyBlack\"], img[src*=\"ruby\"]",
    },
    navigation: {
        garageCategory: ".MenuComponentStyle-mainMenuItem",
        activeGarageCategory: ".MenuComponentStyle-mainMenuItem.-activeMenu",
        mountedBlock: "[class*=\"MountedItemsStyle-commonBlock\"]",
        equipmentItem: "[class*=\"Item\"], [class*=\"item\"], [class*=\"Equipment\"], [class*=\"equipment\"]",
        backControls: ".BreadcrumbsComponentStyle-backButton, .IconStyle-iconBackArrow, [class*=\"backButton\" i]",
        header: ".BreadcrumbsComponentStyle-headerContainer",
        title: ".BreadcrumbsComponentStyle-rootTitle > span",
        back: ".BreadcrumbsComponentStyle-backButton",
        primaryItem: ".PrimaryMenuItemComponentStyle-itemCommonLi.PrimaryMenuItemComponentStyle-menuItemContainer",
        settingsIcon: ".PrimaryMenuItemComponentStyle-itemLiOption",
        primaryItemName: ".PrimaryMenuItemComponentStyle-itemName",
        settingsContent: ".SettingsComponentStyle-container",
        footerList: ".FooterComponentStyle-footer ul",
    },
    garage: {
        item: ".garage-item",
        itemImage: ".GarageItemComponentStyle-mainImg",
        itemName: ".ItemDescriptionComponentStyle-nameItem",
        itemDescription: ".GarageItemComponentStyle-descriptionDevice span",
        weaponName: ".ItemDescriptionComponentStyle-nameItem span, .GarageItemComponentStyle-descriptionDevice span",
        upgradeTitles: ".ItemDescriptionComponentStyle-nameItem span, .GarageItemComponentStyle-descriptionDevice span, .MountedItemsStyle-tankPartNameContainer h1",
        deviceIcon: ".DeviceButtonComponentStyle-deviceIcon",
        priceButton: ".SquarePriceButtonComponentStyle-commonBlockButton",
        maxPriceTitle: ".SquarePriceButtonComponentStyle-commonBlockButton h2",
        actionContainer: ".TanksPartBaseComponentStyle-buttonsContainer",
        mountContainer: ".TanksPartBaseComponentStyle-marginTop",
        established: ".TanksPartBaseComponentStyle-marginTop .-buttonEstablished",
        coinIcon: ".GarageCommonStyle-iconCoinSmall",
        actionButton: ".GarageCommonStyle-bigActionButton",
        styledActions: ".GarageCommonStyle-bigActionButton, .AlterationButtonStyle-commonButton",
        weaponActions: ".GarageCommonStyle-bigActionButton, .SquarePriceButtonComponentStyle-commonBlockButton",
        suppliesActions: ".GarageSuppliesComponentStyle-containerButtons",
        mountedEquipment: ".MountedItemsStyle-commonBlockForTurretsHulls",
        mountedPreview: ".MountedItemsStyle-itemPreview",
        submenu: ".GarageCommonStyle-subMenu",
    },
    augments: {
        cardImage: "img.SkinCellStyle-iconCell",
        rewardImageBlock: ".RewardCardComponentStyle-imageBlock",
        possibleRewards: ".ContainersComponentStyle-possibleRewardsBlock",
    },
    skins: {
        cards: ".SkinsAndAlterationsStyle-SkinsVerticalComponent",
        cardTitle: ".SkinCellStyle-nameDevices",
        cardIcon: ".SkinCellStyle-iconCell",
        equippedIcon: ".SkinCellStyle-mountIcon",
    },
    paints: {
        caption: ".PaintsCollectionComponentStyle-captionPaint",
        categoryInfo: ".PaintsCollectionComponentStyle-commonBlockFOrInfoAndCaptionCategory",
        items: ".ListItemsComponentStyle-itemsContainer",
    },
    friends: {
        lists: ".FriendListComponentStyle-scrollCommunity, .InvitationWindowsComponentStyle-usersScroll",
        card: ".FriendListComponentStyle-blockList",
        invitationCard: ".InvitationWindowsComponentStyle-usersScroll > div > div",
        online: ".FriendListComponentStyle-greenTextOnline",
        offline: ".FriendListComponentStyle-offline",
        contextMenu: ".ContextMenuStyle-menu",
        contextPlayer: ".ContextMenuStyle-menuItemRank",
    },
    play: {
        disabled: ".MainScreenComponentStyle-disabledButtonPlay",
        cards: ".BattlePickComponentStyle-commonStyleBlock, .blockCard, [class*=\"commonStyleBlock\"]",
        container: ".MainScreenComponentStyle-playButtonContainer",
        untreatedContainer: ".MainScreenComponentStyle-playButtonContainer:not([data-overridden=\"true\"])",
        button: ".MainScreenComponentStyle-buttonPlay",
        mainMenu: ".MainScreenComponentStyle-blockMainMenu",
    },
    trophies: {
        rewardImage: "[class*=\"rewardsContainer\"] [class*=\"-backgroundImageContain\"]",
        cards: ".MainQuestComponentStyle-cardPlayCommon, .TableMainQuestComponentStyle-commonTableMainQuest, .MainQuestComponentStyle-cardPlay",
        favorite: ".PaintsCollectionComponentStyle-favoriteIconContainer",
        resultText: ".BattleResultQuestProgressComponentStyle-text",
        resultCards: ".BattleResultQuestProgressComponentStyle-container",
        lobbyAnchor: ".BattlePassLobbyComponentStyle-menuBattlePass",
    },
    statistics: {
        container: ".BattleTabStatisticComponentStyle-container",
        nickname: ".BattleTabStatisticComponentStyle-nicknameCell",
        nicknameText: ".BattleTabStatisticComponentStyle-nicknameCell span",
        equipment: ".BattleTabStatisticComponentStyle-commonBlock",
        selectedRow: ".BattleTabStatisticComponentStyle-selectedRowBackGround",
        deviceCell: ".BattleTabStatisticComponentStyle-deviceCell",
        hullCell: ".BattleTabStatisticComponentStyle-defenceCell",
        teams: ".BattleTabStatisticComponentStyle-containerInsideTeams, .BattleTabStatisticComponentStyle-containerInsideResults",
        headerRows: ":is(.BattleTabStatisticComponentStyle-containerInsideTeams, .BattleTabStatisticComponentStyle-containerInsideResults) table thead tr",
        resistanceCell: ".BattleTabStatisticComponentStyle-resistanceModuleCell",
        options: ".BattleTabStatisticComponentStyle-commonContainerIconOptions",
    },
    results: {
        selfRow: "#selfUserBg",
        columnPrefix: ".BattleKillBoardComponentStyle-col",
        playerName: "[class*=\"BattleKillBoardComponentStyle-col1\"] span.-whiteSpaceNoWrap",
        nicknameCell: ".BattleKillBoardComponentStyle-col1, [class*=\"BattleKillBoardComponentStyle-col1\"]",
        rankIcon: ".BattleKillBoardComponentStyle-rankIcon",
        gearScore: ".BattleKillBoardComponentStyle-col2 span",
        score: ".BattleKillBoardComponentStyle-col3",
        kills: ".BattleKillBoardComponentStyle-col4",
        deaths: ".BattleKillBoardComponentStyle-col5",
        kd: ".BattleKillBoardComponentStyle-col6",
        stars: ".BattleKillBoardComponentStyle-col8",
        body: ".TableComponentStyle-tBody",
        mapName: ".BattleResultHeaderComponentStyle-mapName",
        status: ".BattleResultHeaderComponentStyle-resultText",
        statusFallback: "[class*=\"descriptionVictory\"], [class*=\"descriptionDefeat\"], [class*=\"descriptionDraw\"]",
        firstTeamScore: ".BattleResultHeaderComponentStyle-firstTeamAccount .BattleResultHeaderComponentStyle-teamAccount",
        secondTeamScore: ".BattleResultHeaderComponentStyle-twoTeamAccount .BattleResultHeaderComponentStyle-teamAccount",
    },
    classes: {
        wideGarageButton: "-widthHeightButtonGarage",
        activeMenu: "-activeMenu",
        upgradeTransition: "GarageCommonStyle-animatedBlurredRightBlock",
        upgradeButton: "SquarePriceButtonComponentStyle-commonBlockButton -commonButtonUpdate -flexCenterAlignCenter -displayFlex -alignCenter",
        footerEntry: "FooterComponentStyle-containerMenu",
        friendList: "FriendListComponentStyle-scrollCommunity",
        disabledPlay: "MainScreenComponentStyle-disabledButtonPlay",
        gridTrophy: "MainQuestComponentStyle-cardPlay",
        favorite: "PaintsCollectionComponentStyle-favoriteIconContainer",
        defenceLabel: "BattleTabStatisticComponentStyle-defenceLabel",
        flexCenter: "-flexCenterAlignCenter",
        mask: "-maskImageContain -maskImage",
        regular: "-regular",
        normal: "-normal",
        flexStart: "-flexStart",
    },
    ids: {
        selfRow: "selfUserBg",
        spacer: "rowSpace",
        teamDivider: "teamRowSpace",
    },
    fragments: {
        nicknameText: "whiteSpaceNoWrap",
        header: "header",
    },
} as const;
